---

- name: apt-get update the server
  apt: update_cache=yes
  when: ansible_os_family == "Ubuntu"

- name: yum update the server
  yum: update_cache=yes
  when: ansible_os_family == "Redhat"
