---

- name: Install MySQL server
  package: name=mysql-server state=latest

- name: Install Apache module for MySQL authentication
  package: name=libapache2-mod-auth-mysql state=latest

- name: Install MySQL module for PHP
  package: name=php-mysql state=latest
  
- name: Install Python MySQLdb
  package: name=python-mysqldb state=latest

- name: Create the Drupal database
  mysql_db: db={{ db_name }} state=present

- name: Create the Drupal user
  mysql_user: >
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name }}.*:ALL
    host=localhost
